# Configuration Read the Docs
# Voir https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Configuration du build
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Configuration Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Formats de documentation à générer
formats:
  - pdf
  - epub

# Installation Python
python:
  install:
    # Installer le backend avec les dépendances docs
    - method: pip
      path: backend
      extra_requirements:
        - docs
    # Installer le frontend avec les dépendances docs
    - method: pip
      path: frontend
      extra_requirements:
        - docs
