services:
  mange-ta-main-back:
    build:
      context: ./backend
      target: prod
    image: mange_ta_main:prod

  mange-ta-main-front:
    build:
      context: ./frontend
      target: prod
    image: mange-ta-main-front:prod

  