services:
  mange-ta-main-back:
    build:
      context: .
      target: dev
    image: mange_ta_main:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock